name: Deploy Laravel to Alwaysdata

on:
  push:
    branches:
      - main  # убедитесь, что ваша ветка называется main, а не master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sync files via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ssh-dndsite.alwaysdata.net
          username: ${{ secrets.ALWAYSDATA_SSH_USER }}
          password: ${{ secrets.ALWAYSDATA_SSH_PASSWORD }}
          port: 22
          protocol: sftp # ОБЯЗАТЕЛЬНО: указываем экшену использовать SFTP вместо FTP
          server-dir: /
