name: Deploy Laravel to Alwaysdata

on:
  push:
    branches:
      - main  # Ваша рабочая ветка

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files via SSH/SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.ALWAYSDATA_SSH_USER }}
          password: ${{ secrets.ALWAYSDATA_SSH_PASSWORD }}
          server: ssh-dndsite.alwaysdata.net
          port: 22
          local_path: './*'        
          remote_path: '.'         # Изменено: загружаем прямо в домашнюю директорию пользователя
          delete_remote_files: false 
